version: 2
registries:
  wex-github:
    type: rubygems-server
    url: https://rubygems.org
    token: ${{secrets.WEX_GITHUB_TOKEN}}
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: aasm
    versions:
    - "< 6"
    - ">= 5.a"
  - dependency-name: rails
    versions:
    - "< 6"
    - ">= 5.a"
