---
enable_multisite:
  active: <%= ENV.fetch("ENABLE_MULTISITE", "false") %>
enable_interactive_map:
  active: <%= ENV.fetch("ENABLE_INTERACTIVE_MAP", "false") %>
restrict_site_locations_to_england:
  active: <%= ENV.fetch("RESTRICT_SITE_LOCATIONS_TO_ENGLAND", "false") %>
